[build]
  functions = "src/lambda/"
  publish = "dist/"
  command = "npm run build"

[template.environment]
  API_TOKEN = "your Google Maps API key"

[[redirects]]
from="/api"
to=".netlify/functions/getapi"
status=200
